-- [nfnl] Compiled from fnl/config/keymaps.fnl by https://github.com/Olical/nfnl, do not edit.
local _local_1_ = require("nfnl.module")
local autoload = _local_1_["autoload"]
local core = autoload("nfnl.core")
local _local_2_ = autoload("config.utils")
local noremap = _local_2_["noremap"]
local llmap = _local_2_["llmap"]
noremap("n", "<C-s>", ":update!<CR>")
noremap("i", "<C-s>", "<ESC>:update!<CR>")
noremap("i", "jk", "<esc>")
noremap("c", "jk", "<c-c>")
noremap("t", "jk", "<c-\\><c-n>")
noremap("n", "<C-h>", "<C-w>h")
noremap("n", "<C-j>", "<C-w>j")
noremap("n", "<C-k>", "<C-w>k")
noremap("n", "<C-l>", "<C-w>l")
noremap("n", "<C-S-h>", "<cmd>tabprevious<cr>")
noremap("n", "<C-S-k>", "<cmd>tabclose<cr>")
noremap("n", "<C-S-l>", "<cmd>tabnext<cr>")
noremap("n", "<C-Up>", ":resize -2<CR>")
noremap("n", "<C-Down>", ":resize +2<CR>")
noremap("n", "<C-Left>", ":vertical resize -2<CR>")
noremap("n", "<C-Right>", ":vertical resize +2<CR>")
noremap("v", "<", "<gv")
noremap("v", ">", ">gv")
noremap("x", "J", ":move '>+1<CR>gv-gv")
noremap("x", "K", ":move '<-2<CR>gv-gv")
noremap("x", "<m-j>", ":move '>+1<CR>gv-gv")
noremap("x", "<m-k>", ":move '<-2<CR>gv-gv")
noremap("v", "<m-j>", ":m .+1<CR>==")
noremap("v", "<m-k>", ":m .-2<CR>==")
noremap("v", "p", "\"_dP")
noremap("n", "<m-s>", "<cmd>split<CR>")
noremap("n", "<m-t>", "<cmd>vsplit<CR>")
noremap("n", "<m-m>", "<cmd>bprev<CR>")
noremap("n", "<m-i>", "<cmd>bnext<CR>")
noremap("n", "<c-d>", "<c-d>zz")
noremap("n", "<c-u>", "<c-u>zz")
noremap("n", "<m-n>", "<cmd>nohlsearch<CR>")
noremap("n", "Q", "<cmd>:q<CR>")
return noremap("n", "-", "<cmd>:Explore<cr>")
