-- [nfnl] Compiled from fnl/config/keymaps.fnl by https://github.com/Olical/nfnl, do not edit.
local _local_1_ = require("nfnl.module")
local autoload = _local_1_["autoload"]
local core = autoload("nfnl.core")
local utils = autoload("config.utils")
local function map(mode, from, to)
  return utils.noremap(mode, from, to)
end
map("n", "<C-s>", ":update!<CR>")
map("i", "<C-s>", "<ESC>:update!<CR>")
map("i", "jk", "<esc>")
map("c", "jk", "<c-c>")
map("t", "jk", "<c-\\><c-n>")
map("n", "<C-h>", "<C-w>h")
map("n", "<C-j>", "<C-w>j")
map("n", "<C-k>", "<C-w>k")
map("n", "<C-l>", "<C-w>l")
map("n", "<C-S-h>", "<cmd>tabprevious<cr>")
map("n", "<C-S-k>", "<cmd>tabclose<cr>")
map("n", "<C-S-l>", "<cmd>tabnext<cr>")
map("n", "<C-Up>", ":resize -2<CR>")
map("n", "<C-Down>", ":resize +2<CR>")
map("n", "<C-Left>", ":vertical resize -2<CR>")
map("n", "<C-Right>", ":vertical resize +2<CR>")
map("v", "<", "<gv")
map("v", ">", ">gv")
map("x", "J", ":move '>+1<CR>gv-gv")
map("x", "K", ":move '<-2<CR>gv-gv")
map("x", "<m-j>", ":move '>+1<CR>gv-gv")
map("x", "<m-k>", ":move '<-2<CR>gv-gv")
map("v", "<m-j>", ":m .+1<CR>==")
map("v", "<m-k>", ":m .-2<CR>==")
map("v", "p", "\"_dP")
map("n", "<m-s>", "<cmd>split<CR>")
map("n", "<m-t>", "<cmd>vsplit<CR>")
map("n", "<m-m>", "<cmd>bprev<CR>")
map("n", "<m-i>", "<cmd>bnext<CR>")
map("n", "<c-d>", "<c-d>zz")
map("n", "<c-u>", "<c-u>zz")
map("n", "<m-n>", "<cmd>nohlsearch<CR>")
map("n", "Q", "<cmd>:q<CR>")
map("n", "-", "<cmd>:Explore<cr>")
map("n", "gd", "<Cmd>lua vim.lsp.buf.definition()<CR>")
map("n", "gD", "<Cmd>lua vim.lsp.buf.declaration()<CR>")
map("n", "gi", "<Cmd>lua vim.lsp.buf.implementation()<CR>")
return map("n", "K", "<Cmd>lua vim.lsp.buf.hover()<CR>")
