-- [nfnl] Compiled from fnl/config/keymaps.fnl by https://github.com/Olical/nfnl, do not edit.
local _local_1_ = require("config.utils")
local noremap = _local_1_["noremap"]
local lnoremap = _local_1_["lnoremap"]
noremap("n", "<C-s>", ":update!<CR>", "Save file")
noremap("i", "<C-s>", "<ESC>:update!<CR>", "Save file")
lnoremap("n", "Q", "<Cmd>%bd|e#<cr>", "Close all but current buffer")
noremap("i", "jk", "<esc>", "Leave mode")
noremap("i", "<esc>", "<esc>", "Leave mode")
noremap("c", "jk", "<C-c>", "Leave mode")
noremap("t", "jk", "<C-\\><c-n>", "Leave mode")
noremap("n", "<C-h>", "<C-w>h")
noremap("n", "<C-j>", "<C-w>j")
noremap("n", "<C-k>", "<C-w>k")
noremap("n", "<C-l>", "<C-w>l")
noremap("n", "<C-S-h>", "<cmd>tabprevious<cr>")
noremap("n", "<C-S-k>", "<cmd>tabclose<cr>")
noremap("n", "<C-S-l>", "<cmd>tabnext<cr>")
noremap("n", "<C-Up>", ":resize -2<CR>")
noremap("n", "<C-Down>", ":resize +2<CR>")
noremap("n", "<C-Left>", ":vertical resize -2<CR>")
noremap("n", "<C-Right>", ":vertical resize +2<CR>")
noremap("v", "<", "<gv")
noremap("v", ">", ">gv")
noremap("x", "J", ":move '>+1<CR>gv-gv")
noremap("x", "K", ":move '<-2<CR>gv-gv")
noremap("x", "<C-j>", ":move '>+1<CR>gv-gv")
noremap("x", "<C-k>", ":move '<-2<CR>gv-gv")
noremap("v", "<C-j>", ":m .+1<CR>==")
noremap("v", "<C-k>", ":m .-2<CR>==")
noremap("v", "p", "\"_dP")
noremap("n", "<C-S-s>", "<cmd>split<CR>")
noremap("n", "<C-S-t>", "<cmd>vsplit<CR>")
noremap("n", "<C-m>", "<cmd>bprev<CR>", "Previous buffer")
noremap("n", "<C-i>", "<cmd>bnext<CR>", "Next buffer")
noremap("n", "<C-d>", "<c-d>zz", "Move screen down")
noremap("n", "<C-u>", "<c-u>zz", "Move screen up")
lnoremap("n", "<C-S-n>", "<cmd>nohlsearch<CR>", "Clear highlights")
lnoremap("n", "<C-Q>", "<cmd>:q<CR>", "Quit")
return noremap("n", "-", "<Cmd>:Explore<cr>")
